# Generated by Django 4.2.30 on 2026-06-07 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись журнала', 'verbose_name_plural': 'Журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='adaptationlevel',
            options={'ordering': ['name'], 'verbose_name': 'Уровень адаптации', 'verbose_name_plural': 'Уровни адаптации'},
        ),
        migrations.AlterModelOptions(
            name='communicationlevel',
            options={'ordering': ['name'], 'verbose_name': 'Уровень общения', 'verbose_name_plural': 'Уровни общения'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='familyincomelevel',
            options={'ordering': ['name'], 'verbose_name': 'Материальное положение', 'verbose_name_plural': 'Уровни материального положения'},
        ),
        migrations.AlterModelOptions(
            name='familytype',
            options={'ordering': ['name'], 'verbose_name': 'Тип семьи', 'verbose_name_plural': 'Типы семьи'},
        ),
        migrations.AlterModelOptions(
            name='groupbehaviortype',
            options={'ordering': ['name'], 'verbose_name': 'Поведение в группе', 'verbose_name_plural': 'Типы поведения в группе'},
        ),
        migrations.AlterModelOptions(
            name='healthgroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа здоровья', 'verbose_name_plural': 'Группы здоровья'},
        ),
        migrations.AlterModelOptions(
            name='housingtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип жилья', 'verbose_name_plural': 'Типы жилья'},
        ),
        migrations.AlterModelOptions(
            name='paymentform',
            options={'ordering': ['name'], 'verbose_name': 'Форма оплаты', 'verbose_name_plural': 'Формы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='responsibilitylevel',
            options={'ordering': ['name'], 'verbose_name': 'Уровень ответственности', 'verbose_name_plural': 'Уровни ответственности'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentacademic',
            options={'verbose_name': 'Учебная деятельность', 'verbose_name_plural': 'Учебная деятельность'},
        ),
        migrations.AlterModelOptions(
            name='studentaianalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'ИИ-анализ', 'verbose_name_plural': 'ИИ-анализы'},
        ),
        migrations.AlterModelOptions(
            name='studentbenefits',
            options={'verbose_name': 'Льготы и поддержка', 'verbose_name_plural': 'Льготы и поддержка'},
        ),
        migrations.AlterModelOptions(
            name='studentfamily',
            options={'verbose_name': 'Семья студента', 'verbose_name_plural': 'Семьи студентов'},
        ),
        migrations.AlterModelOptions(
            name='studentfamilymember',
            options={'verbose_name': 'Член семьи', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.AlterModelOptions(
            name='studenthousing',
            options={'verbose_name': 'Жилищные условия', 'verbose_name_plural': 'Жилищные условия'},
        ),
        migrations.AlterModelOptions(
            name='studentmedical',
            options={'verbose_name': 'Медицинские сведения', 'verbose_name_plural': 'Медицинские сведения'},
        ),
        migrations.AlterModelOptions(
            name='studentpsychoprofile',
            options={'verbose_name': 'Социально-психологический профиль', 'verbose_name_plural': 'Социально-психологические профили'},
        ),
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ['name'], 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='temperamenttype',
            options={'ordering': ['name'], 'verbose_name': 'Темперамент', 'verbose_name_plural': 'Типы темперамента'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['name'], 'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('view_sensitive', 'Просмотр чувствительных данных')], max_length=30, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='adaptationlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='adaptationlevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='adaptationlevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='adaptationlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='communicationlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='communicationlevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='communicationlevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='communicationlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='familyincomelevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='familyincomelevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='familyincomelevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='familyincomelevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='familytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='groupbehaviortype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='groupbehaviortype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='groupbehaviortype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='groupbehaviortype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='healthgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='healthgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='healthgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='healthgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='housingtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='housingtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='housingtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='housingtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='responsibilitylevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='responsibilitylevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='responsibilitylevel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='responsibilitylevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.CharField(max_length=120, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.studygroup', verbose_name='Учебная группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='iin',
            field=models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИИН должен содержать ровно 12 цифр.')], verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=120, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentform', verbose_name='Форма оплаты'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.specialty', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='activity',
            field=models.TextField(blank=True, verbose_name='Внеучебная активность'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='attendance',
            field=models.CharField(blank=True, choices=[('good', 'Хорошая'), ('satisfactory', 'Удовлетворительная'), ('problematic', 'Проблемная')], max_length=20, verbose_name='Посещаемость'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='has_unexcused_absences',
            field=models.BooleanField(default=False, verbose_name='Пропуски без уважительной причины'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='unexcused_absences_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пропусков'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='disclaimer',
            field=models.CharField(default='Вывод сформирован автоматически и требует проверки ответственным сотрудником', max_length=255, verbose_name='Дисклеймер'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='recommendations',
            field=models.TextField(verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='risk_factors',
            field=models.TextField(verbose_name='Факторы риска'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='short_profile',
            field=models.TextField(verbose_name='Краткий профиль'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='strengths',
            field=models.TextField(verbose_name='Сильные стороны'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentaianalysis',
            name='support_level',
            field=models.CharField(choices=[('none', 'Не требуется'), ('observe', 'Желательно наблюдение'), ('curator_attention', 'Рекомендуется внимание куратора'), ('specialist', 'Рекомендуется подключение профильного специалиста')], max_length=30, verbose_name='Уровень сопровождения'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='additional_benefits',
            field=models.TextField(blank=True, verbose_name='Дополнительные льготы'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='breadwinner_loss_allowance',
            field=models.BooleanField(default=False, verbose_name='Пособие по потере кормильца'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='disability_allowance',
            field=models.BooleanField(default=False, verbose_name='Пособие по инвалидности'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='free_meals',
            field=models.BooleanField(default=False, verbose_name='Бесплатное питание'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='preferential_housing',
            field=models.BooleanField(default=False, verbose_name='Льготное жильё'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='receives_scholarship',
            field=models.BooleanField(default=False, verbose_name='Стипендия'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='state_grant',
            field=models.BooleanField(default=False, verbose_name='Государственный грант'),
        ),
        migrations.AlterField(
            model_name='studentbenefits',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentfamily',
            name='family_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familytype', verbose_name='Тип семьи'),
        ),
        migrations.AlterField(
            model_name='studentfamily',
            name='income_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.familyincomelevel', verbose_name='Материальное положение'),
        ),
        migrations.AlterField(
            model_name='studentfamily',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='birth_year',
            field=models.PositiveSmallIntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.studentfamily', verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='is_guardian',
            field=models.BooleanField(default=False, verbose_name='Опекун'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='is_primary_contact',
            field=models.BooleanField(default=False, verbose_name='Основной контакт'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='relation',
            field=models.CharField(max_length=120, verbose_name='Степень родства'),
        ),
        migrations.AlterField(
            model_name='studentfamilymember',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='studenthousing',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='studenthousing',
            name='housing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.housingtype', verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='studenthousing',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='disability_details',
            field=models.TextField(blank=True, verbose_name='Сведения об инвалидности'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='has_disability',
            field=models.BooleanField(default=False, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='health_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.healthgroup', verbose_name='Группа здоровья'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='recommendations',
            field=models.TextField(blank=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='studentmedical',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='adaptation_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adaptationlevel', verbose_name='Уровень адаптации'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='behavior_in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.groupbehaviortype', verbose_name='Поведение в группе'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.communicationlevel', verbose_name='Уровень общения'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='responsibility_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.responsibilitylevel', verbose_name='Уровень ответственности'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psycho', to='core.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentpsychoprofile',
            name='temperament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.temperamenttype', verbose_name='Темперамент'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='temperamenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='temperamenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='temperamenttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='temperamenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, to='core.department', verbose_name='Кафедры'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
