# Generated by Django 4.2.30 on 2026-08-27 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_student_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude (Anthropic)')], default='openai', max_length=20, verbose_name='Провайдер')),
                ('model', models.CharField(default='gpt-4o-mini', max_length=80, verbose_name='Модель')),
                ('api_key', models.CharField(blank=True, max_length=512, verbose_name='API-ключ')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Использовать внешнюю модель')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Настройки ИИ',
                'verbose_name_plural': 'Настройки ИИ',
            },
        ),
    ]
