from django.urls import path

from . import admin_views, cabinet_views, views

urlpatterns = [
    path("", views.home, name="home"),
    path("assistant/ask/", views.assistant_ask, name="assistant-ask"),
    path("students/", views.student_list, name="student-list"),
    path("students/create/", views.student_create, name="student-create"),
    path("students/<int:pk>/", views.student_detail, name="student-detail"),
    path("students/<int:pk>/edit/", views.student_update, name="student-update"),
    path("students/<int:pk>/family/", views.family_edit, name="family-edit"),
    path("students/<int:pk>/family/member/create/", views.family_member_create, name="family-member-create"),
    path("students/<int:pk>/family/member/<int:member_id>/delete/", views.family_member_delete, name="family-member-delete"),
    path("students/<int:pk>/housing/", views.housing_edit, name="housing-edit"),
    path("students/<int:pk>/psycho/", views.psycho_edit, name="psycho-edit"),
    path("students/<int:pk>/academic/", views.academic_edit, name="academic-edit"),
    path("students/<int:pk>/medical/", views.medical_edit, name="medical-edit"),
    path("students/<int:pk>/benefits/", views.benefits_edit, name="benefits-edit"),
    path("students/<int:pk>/ai/generate/", views.ai_generate, name="ai-generate"),
    path("ai-analytics/", views.ai_analytics_page, name="ai-analytics"),
    path("reports/", views.reports_page, name="reports"),
    path("reports/export/<str:report_key>/<str:fmt>/", views.export_report, name="report-export"),
    path("action-logs/", views.action_logs, name="action-logs"),
    path("administration/logs/", admin_views.admin_logs, name="admin-logs"),
    path("settings/", views.settings_page, name="settings"),
    path("settings/references/<str:key>/<int:pk>/edit/", views.reference_edit, name="reference-edit"),
    path("settings/references/<str:key>/<int:pk>/toggle/", views.reference_toggle, name="reference-toggle"),
    path("settings/users/create/", views.user_create, name="user-create"),
    path("settings/users/<int:pk>/edit/", views.user_edit, name="user-edit"),
    path("administration/", admin_views.admin_overview, name="admin-panel"),
    path("administration/users/", admin_views.admin_users, name="admin-users"),
    path("administration/users/create/", admin_views.admin_user_create, name="admin-user-create"),
    path("administration/users/<int:pk>/edit/", admin_views.admin_user_edit, name="admin-user-edit"),
    path("administration/users/<int:pk>/toggle-block/", admin_views.admin_user_toggle_block, name="admin-user-toggle-block"),
    path("administration/users/<int:pk>/logout-all/", admin_views.admin_user_logout_all, name="admin-user-logout-all"),
    path("administration/sessions/", admin_views.admin_sessions, name="admin-sessions"),
    path("administration/sessions/<str:session_key>/terminate/", admin_views.admin_session_terminate, name="admin-session-terminate"),
    path("administration/roles/", admin_views.admin_roles, name="admin-roles"),
    path("administration/roles/<int:pk>/edit/", admin_views.admin_role_edit, name="admin-role-edit"),
    path("administration/roles/<int:pk>/toggle/", admin_views.admin_role_toggle, name="admin-role-toggle"),
    path("administration/groups/", admin_views.admin_groups, name="admin-groups"),
    path("administration/groups/create/", admin_views.admin_group_edit, name="admin-group-create"),
    path("administration/groups/<int:pk>/edit/", admin_views.admin_group_edit, name="admin-group-edit"),
    path("administration/ai/", admin_views.admin_ai_settings, name="admin-ai"),
    path("cabinet/login/", cabinet_views.cabinet_login, name="cabinet-login"),
    path("cabinet/logout/", cabinet_views.cabinet_logout, name="cabinet-logout"),
    path("cabinet/", cabinet_views.cabinet_home, name="cabinet-home"),
    path("cabinet/profile/", cabinet_views.cabinet_profile, name="cabinet-profile"),
    path("cabinet/family/", cabinet_views.cabinet_family, name="cabinet-family"),
    path("cabinet/family/member/add/", cabinet_views.cabinet_family_member_add, name="cabinet-family-member-add"),
    path("cabinet/family/member/<int:member_id>/delete/", cabinet_views.cabinet_family_member_delete, name="cabinet-family-member-delete"),
    path("cabinet/housing/", cabinet_views.cabinet_housing, name="cabinet-housing"),
    path("cabinet/requests/", cabinet_views.cabinet_requests, name="cabinet-requests"),
    path("cabinet/password/", cabinet_views.cabinet_password, name="cabinet-password"),
]
